language: python
python: 3.7
script: skip
deploy:
  provider: pypi
  user: kpn-digital
  skip_cleanup: tru
  password:
    secure: lYKlj+TuGHDfrbvnspgfFChlEc941hraNiuqlAkrwv5PMZrKEPoYMfzFq/36bkAXmfMJdIMo4saqAi+INop5eShsnJkFaPxTc2uEx9FXvTFsZQ8qPHhQUpAYKkSvyGh9PtHwg77PZtARct+HzaS8kEKIT0i9h4hslHhlkqVqzqDAz/J8uOSJ0/8Agk51wVdEYStLL7po1eCKkvBjEaORjSt1cqIHrIrlGYrpp7lgK2u2L4ai4WMuAMCezHaYPFQOI6Aa20nFRRGNL2V5LbSZGU6A5tYLsYk4OoqSZ05JC6d5dBYPANQ+Njz3nd+dtgz/xlffIwl8Eu7czZdVIbM4lOdloiLsoEtw+h/WGyeHiYjXdvaubFYhN91ZFO2OOL/mrEFGEnpEzIHwh3BJ8uFxJi8hcb5BIvLQ+ySnMJu6t9dDyCKYJla025fRAOtqbWgbfe+x2RpUtizNZFu66CJ33U1FP83iDB/PgHxMprKa7UsUJikmUFLLkT/aKhBCcm5NpLyx8rQCvHMTMgI9taRYehynu2u6bx9rrDh9UsmaGxCQvaV7CqP8Z9i/dVSHwjjYa0CZEf+GMRkJ/aNxheaRgIDfEUqfxhTys4tzrBge6jl220dYhCUdOSjKS+2p/0JrUHQA+JfMHbCTtXrx1+1I0SbJ28YjHRTB0uBFt1xC1mc=
  on:
    tags: true
    all_branches: true
